### ISSUE TITLE
CallRecipient doesn't have fromNumber

### ISSUE THREAD

**Issue by bfcamara** [CallFire/callfire-api-client-csharp#51]
From swagger https://www.callfire.com/v2/swagger-ui/index.html#!/calls/sendCalls I can see that the `CallRecipeint` has a propery `fromNumber`. This property is not available in this SDK. Shoudn't be included in SDK as well?

**Comment by vmalinovskiy** [comment]
Hi, yes, it should be included in the next release.

**Comment by bfcamara** [comment]
Hi @vmalinovskiy, 

any ETA for the next release?

**Comment by vladimir-mhl** [comment]
fixed
