### ISSUE TITLE
System.IO.FileLoadException

### ISSUE THREAD

**Issue by d4hines** [CallFire/callfire-api-client-csharp#55]
Hello,
I'm hitting the following error at _runtime_ in one my of tests
>System.IO.FileLoadException : Could not load file or assembly 'callfire-api-client, Version=1.1.19.29318, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

What does this error mean, and how can I resolve it?
Thanks,
Daniel Hines

**Comment by vmalinovskiy** [comment]
Could you please share your test to be able to reproduce. 
How did you installed dll? Please check this doc: 
https://developers.callfire.com/callfire-api-client-csharp.html

**Comment by d4hines** [comment]
@vmalinovskiy, I created a repo with my code so far: https://github.com/d4hines/example-callfire-client-error.

Thanks for pointing me to that doc - I missed that. Unfortunately, however, adding the copy command did not fix the issue.

Thanks for your help on this.

**Comment by d4hines** [comment]
Update: In the main project, `CallFirePlugin.Plugins`, in unchecking "Sign the assembly" under "Properties" > "Signing" allows the project to run successfully. However, I'm unsure at the moment whether unsigned assemblies are workable in our sitaution.

**Comment by ZelNaga** [comment]
Hello. 
It is fixed now
