### ISSUE TITLE
RestSharp Issue or Callfire's not sure

### ISSUE THREAD

**Issue by archergod** [CallFire/callfire-api-client-csharp#62]
We assume it is RestSharp issue, but when using `TextApi.Send` we are getting following error:

     Method not found: 'Void RestSharp.RestRequest..ctor(System.String, RestSharp.Method)'.

We point it out to RestSharp issue here: https://github.com/restsharp/RestSharp/issues/1198 Can you please help determine the issue. Thanks.

**Comment by vmalinovskiy** [comment]
Please revert RestSharp to 106.4.2 as workaround for now.

**Comment by archergod** [comment]
Thanks, I already did and it is working fine with 106.4.2

**Comment by vmalinovskiy** [comment]
Updated RestSharp to 106.6 so issues should be fixed.
https://github.com/CallFire/callfire-api-client-csharp/releases/tag/1.1.26
